[build]
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/tiktok/*"
  to = "/.netlify/functions/:splat"
  status = 200
